### ISSUE TITLE
 "Trim and Extend" issues

### ISSUE THREAD

**Issue by Hannes82822** [BjornNyberg/NetworkGT#11]
Hello!

We are currently working on the creation of reachability analysis. We use geometries from OpenStreet Map for this. Anyone who has already dealt with the datasets from Open Street Map will know that the street geometries are not consistently and that in some places individual streets are only individual fragments or isolated components. This issue becomes problematic as soon as individual locations (points) should be connected to the network dataset (ArcGIS) and are not connected to the main component of the network. Individual locations are always captured from the closest point in the network in order to make them available for reachability analysis. However, if the closest point is only a fragment of a street that is not connected to the overall network, the respective location cannot be included in the overall network and the calculation of the reachability for this location is incorrect.
So I tried to remove these individual street fragments with the NetworkGT toolbox (I use QGis 3.14.0-Pi). First, I tried to remove the mentioned fragments from the street geometry of a sample dataset - a small section of the street geometry - with the tool Trim and Extend. With the setting "Remove Short Isolated Fractures Threshold" this process worked so far. I was just a little surprised that when the threshold values were modified, there were no visible changes with respect to the results. The same happened applying "Distance to Trim Dangles". What is the actual unit of the thresholds? Meters? Segments?
After I finally edited the entire shape file with the street geometries with the Tool Trim and Extend (threshold value 1), I found that the attribute table of the output file, contrary to my expectations, contains more data records than the input file (input file: 4,861,883 data sets, output file: 4,892,872 data sets). At the same time, there were blank entries in 78 percent of the data records in the attribute table of the output file. Would I have had to make some other settings beforehand? Has the problem occurred before? Could it be that the shape file contains too many data records? Do I need to use a different version of QGIS?
I hope you can help me.

Best regards
Hannes

**Comment by BjornNyberg** [comment]
@Hannes82822 

Thanks for the query. The NetworkGT toolkit is designed primarily to analyse fracture networks so the terminology reflects that. The "Remove Short Isolated Fractures Threshold" will remove polylines below the threshold that are isolated and have no intersection with any other polyline. The "Distance to Trim Dangles" will trim polylines by removing segments of a line that are shorter than the specified distance and have one endpoint without any connection (see Figure 3c from the Wiki). This is archieved by "exploding" the polyline into its branch segments and defining only those end segments that are below the threshold. Hence the reason for the increased number of features. As for the blank enteries I am not sure. Could you provide a sample dataset perhaps? The units are in map units. 

![image](https://user-images.githubusercontent.com/37108459/102334931-8b9b0e00-3f8f-11eb-8594-79b7a5309014.png)
Fig. 3: Schematic of various topological artefacts that can occur during network digitisation and can be corrected using the suite of topological processing tools: A- remove erroneous short isolated fracture lines; B- extend and snap fracture lines to existing fractures; C- trim and snap fracture lines to existing fractures; D- snap I-nodes of incorrectly offset fracture lines; E- Merge fragmented fracture lines that lead to inconsistent node counts; F- snap Y-nodes of incorrectly offset fracture lines.
