### ISSUE TITLE
127.0.0.1:57971 error when opening diagrams 

### ISSUE THREAD

**Issue by kaford315** [BjornNyberg/NetworkGT#12]
Hello Bjorn, 

I'm having some issues opening the output data e.g. rose plots, histograms etc, into my browser, I didn't have this issue previously. I get a 127.0.0.1 error  Any idea what the problem could be? I don't have a proxy or VPN running either. 

Thanks! 

Katie

**Comment by BjornNyberg** [comment]
@kaford315 do you have a default browser set?

**Comment by kaford315** [comment]
the default is set to Chrome, I have tried changing it to Microsoft edge but had the same issue

**Comment by BjornNyberg** [comment]
@kaford315 

Hmm im not sure can you send me a screenshot by email?

**Comment by kaford315** [comment]
sure!

**Comment by BjornNyberg** [comment]
This problem was resolved but the cause of it was not determined. I will keep this issue open for documentation if anyone else has a similar issue.

**Comment by LB72000** [comment]
Hello Bjorn,
I start to use NetworkGT on QGIS. When I try to plot a rose diagram with my data (bin size : 5; No weight field; No group field) I get a 127.0.0.1:50510 error. I use Firefox as browser (same results with chrome). I tried to run the plot both on a wired network and by wifi, but same results.
Any idea how to solve this issue ?

Thanks,
Loïc

**Comment by kaford315** [comment]
Hi Loic,


Maybe I can give some answer,


I also had this issue and we didn't find a cause of the problem but what worked for me was making sure that I was running QGIS as administrator, making sure there was no VPN running, and closing all tabs and windows of the browser that opens the rose plot. So essentially the window opening with your diagram should be the only tab open in that browser.


I hope this helped!


Katie Ford


Geoscientific Center of the University of Göttingen
Structural Geology and Geodynamics
Goldschmidtstr. 3, 37077 Göttingen

Office number: 125


Tel: +49 551 14269

________________________________

**Comment by BjornNyberg** [comment]
Hi @LB72000 ,

Did the answer by @kaford315 solve your problem? Would be good to figure this out as it may affect a lot of people. The inputs used in the rose diagram (as well as any plot) is not an issue but rather lies with plotly creating the plots.

Cheers,
Björn

**Comment by swgeoscience** [comment]
Hi @kaford315 and @BjornNyberg,

I've been having a similar error (using QGIS on Mac). 

Sorry if you've already established this but... It seems to be a problem with the plotting code that I can trace to Line 341 in Topology_Parameters.py where "Figure has no attribute show" is the error ... I get the same error when trying to plot a rose diagram so assume it's the same issue.

From doing some digging this may be an issue with a newer version of plotly? But given this appears to have started recently, perhaps not? That's about the limit of my ability to investigate the error!


![Screenshot 2021-01-14 at 15 39 26](https://user-images.githubusercontent.com/33185384/104617646-98407e00-5683-11eb-8e2d-ddd502055847.png)

**Comment by kaford315** [comment]
Hi Chris,


I think this is a different issue, I had this problem too originally but the solution was just to update plot.ly and run QGIS as administrator. The issue here seems to be that in QGIS the plot runs smoothly with no errors, then when it opens the plot in a browser that already has other tabs open, the 127.0.0.1 error appears. It loads the plot fine if there are no other tabs open. I don't know why!


Hope that made some sense.


Katie


Geoscientific Center of the University of Göttingen
Structural Geology and Geodynamics
Goldschmidtstr. 3, 37077 Göttingen

Office number: 125


Tel: +49 551 14269

________________________________

**Comment by swgeoscience** [comment]
Aha, my mistake! I look forward to encountering this one next :P

**Comment by LB72000** [comment]
Hi @kaford315 and @BjornNyberg,
My issue is fixed. Me and the IT engineer have update the administrator parameters and disenable the "navigation privée" option in Firefox ("private navigation" I guess in english). Now the rose diagram tool runs perfectly.

Thank you very much both of you for advising me.

Loïc
