### ISSUE TITLE
.ix Error in some tools

### ISSUE THREAD

**Issue by sebastianyanez** [BjornNyberg/NetworkGT#13]
Hello Bjorn,

Nowadays i'm working with Network Gt, unfortunately i have a error with the tool, i don't understand what is the problem because i followed the instructions of installations written on pdf for QGIS, just with one exception, i didn't use the direction "http://osgeo4w-oslandia.com" because it didn't download the package. The error doesn't permit me to use some tools of NetworkGt like "Topology Parameters" (attached photo with the error). If you can help me with the problem, I will be very grateful.

![image](https://user-images.githubusercontent.com/80435023/110722039-60bc0100-81f0-11eb-8ce1-73c7251a740e.png)

**Comment by BjornNyberg** [comment]
@sebastianyanez 

Hi .ix indexing was removed in a later version of pandas. Make sure to use the [configure tool](https://github.com/BjornNyberg/NetworkGT/wiki/Installation) and specifically update to pandas==0.25.1.

Does this solve your problem? 

Björn

**Comment by BjornNyberg** [comment]
Will close the issue but feel free to reopen the issue if the problem persists.
