### ISSUE TITLE
Topology Parameters issue

### ISSUE THREAD

**Issue by LB72000** [BjornNyberg/NetworkGT#15]
Hello Bjorn,
When I run the "Topology Parameters" tool on my fracture network, an error message appear :
**_AttributeError: 'DataFrame' object has no attribute 'ix'_**

Before that I only use the "Trim and Extent" and "Define fracture line numbers" tools on my data.
Do you have an idea how I can fix it ?

I try with two fracture networks and it is the same error message.

Thanks!
Loïc

**Comment by BjornNyberg** [comment]
Hi @LB72000 

Please update the tool and use the configuration tool. More info is available at https://github.com/BjornNyberg/NetworkGT/issues/13 or https://github.com/BjornNyberg/NetworkGT/issues/9   

Cheers
Björn
