### ISSUE TITLE
Roadside outcrop

### ISSUE THREAD

**Issue by MaryiR** [BjornNyberg/NetworkGT#18]
Hi!
I would like to know if it is possible to use Networkgt to analyze vertical outcrops. because when I put a photograph into qgis, it will assume it is in map view and the orientation and length of the fractures would be wrong. is there a way to scale the photographs and be able to use the p20 and p21 calculations for this type of outcrops?

thanks,

**Comment by BjornNyberg** [comment]
Hi @MaryiR 

This is possible by taking the unreferenced image from the outcrop and [georeferencing](https://docs.qgis.org/3.22/en/docs/training_manual/forestry/map_georeferencing.html) the image to a map view. For instance, if you know that the outcrop image is 1x1m, then georeference the image to some point in space using a projected coordinate system (e.g., UTM). Each corner of the image is chosen with exactly 1 meter apart. The orientation or dip of the Fractures will be relative to North. 

Keep in mind that most outcrop images are 2.5D representations. If this is the case, I would recommend interpreting the fracture network in a 2.5D space (e.g., [Lime](https://virtualoutcrop.com/lime)) and projecting the interpretations onto a [2D plane](https://virtualoutcrop.com/feature/panels) before interpreting in QGIS. However, if the outcrop is relatively 2D it would be fine to directly import the outcrop images into QGIS.

**Comment by MaryiR** [comment]
Thank you Nyberg.
