### ISSUE TITLE
System cannot find the files specified

### ISSUE THREAD

**Issue by zakmilner** [BjornNyberg/NetworkGT#23]
Hi Bjorn,

I am going through the NetworkGT example using the Hartland fractures. When I run the Rose Diagram Plots tool it gives me this error message:

Traceback (most recent call last):
  File "D:\NetworkGT\NetworkGT-master\ArcGIS\Scripts\WeightedRoseDiagramPlots.py", line 94, in <module>
    main(infc,bins,field,grp)
  File "D:\NetworkGT\NetworkGT-master\ArcGIS\Scripts\WeightedRoseDiagramPlots.py", line 83, in main
    P=subprocess.Popen(expression, shell=False, stdin=None, stdout=None, stderr=None, close_fds=True,creationflags=DETACHED_PROCESS)
  File "D:\ArcGIS\ArcGIS10.5\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\ArcGIS\ArcGIS10.5\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Failed to execute (RoseDiagramPlots).

This also happens when I run most of the tools with my own data. What am I doing wrong?

Cheers,
Zak

**Comment by BjornNyberg** [comment]
Hi Zak,

This may be related to admin access but I am not entirely sure. At the moment I have stopped updating the ArcGIS plugin and opted to support a fully open-source QGIS plugin instead. You can find the details of that plugin here - https://github.com/BjornNyberg/NetworkGT/wiki

Cheers,
Bjorn

**Comment by zakmilner** [comment]
Hi Bjorn, I have now started using QGIS and everything seems to be running fine. Thank you!
