### ISSUE TITLE
Invalid Syntax Python Code Installation File

### ISSUE THREAD

**Issue by fristena** [BjornNyberg/NetworkGT#27]
Hi there, 

I tried to install NetworkGT but already in the Python installation file there seems to be a problem. 

In line 35 _except Exception,e:_ the comma causes an error. 

Do you have any idea why that could be and how to fix it?

Cheers, 
Arabella

**Comment by BjornNyberg** [comment]
Hi @fristena,

Which tool are you trying to run? The [Configure NetworkGT tool ](https://github.com/BjornNyberg/NetworkGT/blob/master/QGIS/network_gt/networkgt/configureNetworkGT.py) does not have an except Exception, e clause as far as I can see?

One solution would be to change it to 

`except Exception as e`

but im not sure why that syntax would specifically solve the issue. What version of QGIS/python do you have?

Edit -  if you are trying to install the ArcGIS version then it does indeed have that [code](https://github.com/BjornNyberg/NetworkGT/blob/master/ArcGIS/Install/Install.py). I have to advise against using ArcGIS though as it is not mainted anymore. It was originally written in python 2.x which has been subsequently discontinued so im not sure if it is still compatible. I would highly recommend using the QGIS version instead with a detailed user guide available [here](https://github.com/BjornNyberg/NetworkGT/wiki/User-Guide).

**Comment by BjornNyberg** [comment]
@fristena 

Im going to assume this issue was related to the ArcGIS version so im going to close this issue for now. Please reopen if that assumption is wrong.
