### ISSUE TITLE
Digitise Fracture Network issue

### ISSUE THREAD

**Issue by xxostars** [BjornNyberg/NetworkGT#28]
hi, I am trying to digitise fracture network but it didn't work 
It says: Error: Algorithm grass7:r.to.vect not found

what should i do? 

<img width="947" alt="Screenshot 2023-04-19 133713" src="https://user-images.githubusercontent.com/127874728/233036164-240962f6-6c1d-4ae6-8e26-5222da8c5e5e.png">

**Comment by BjornNyberg** [comment]
Hi @xxostars 

What version of QGIS do you have? You may have to enable GRASS GIS extension in QGIS by opening the 'Options' button on the processing toolbox (see picture below).

![image](https://user-images.githubusercontent.com/37108459/233043039-74eba996-cece-446b-9ed6-6a6455dd6a82.png)

If you are using a newer version of QGIS (3.28? +), then you need enable GRASS GIS via the plugin manager (Plugins -> manage plugins) and check GRASS GIS provider.

![image](https://user-images.githubusercontent.com/37108459/233050382-48a29dd3-98fc-47d4-bbd6-e47c75cbb158.png)

**Comment by xxostars** [comment]
thankk you so much! its working now
