### ISSUE TITLE
Multiple node intersections

### ISSUE THREAD

**Issue by HunterM02** [BjornNyberg/NetworkGT#29]
When using the branches and nodes tool it is giving an error saying "Found intersection with x nodes at coordinate" As shown in the attached image. After running the Repair Topology tool it gave the error "Null geometry cannot be converted to a polyline" Can you help me understand how to solve this one final error. I am using QGIS 3.20.3 and Windows 10. Thank you in advance.
![Example](https://user-images.githubusercontent.com/131397899/233456669-96c7304f-566d-44f5-9e7f-57343005fa98.png)

**Comment by BjornNyberg** [comment]
@HunterM02 

This is a difficult issue to resolve without seeing an actual example. Could you please send one by email? Does the Repair Topology tool fail with that error or simply reports that there are Null geometries? Sometimes a vector layer will indeed have null geometries that need to be deleted.

Cheers

**Comment by BjornNyberg** [comment]
This issue has been resolved. Datasets were in a geographical coordinate system instead of a projected coordinate system.  Add potential warning if dataset is using a wgs84 projection in the future.
