### ISSUE TITLE
Contour Grid issue

### ISSUE THREAD

**Issue by xxostars** [BjornNyberg/NetworkGT#30]
I need to know based on what shoud i set the spacing and radius numbers? I didn't get the note written in the user guide. 
Help please

**Comment by BjornNyberg** [comment]
Hi @xxostars 

The ideal spacing and radius will depend on the fracture network that you are mapping. One starting point would be to have the radius set at 2 or 4 times your averaged fracture spacing. Contour spacing will depend on the level of detail that your require but make sure that it is lower than the radius.
