### ISSUE TITLE
Error "no module named 'chart_studio'"

### ISSUE THREAD

**Issue by fristena** [BjornNyberg/NetworkGT#33]
Hi there :) 

I installed NetworkGT for QGIS based on the instructions. However, when conducted step 2.1. --> 2. and searched for http://osgeo4w-oslandia.com, the following error message poped up:
![image](https://user-images.githubusercontent.com/130743913/236838048-d67c26a9-12b0-44a2-a1b0-6e06767e94c4.png)

Nevertheless, could still install the packages using one of the suggested download sites (download.osgeo.org).

Now I wanted to try the distribution analysis tool, where following error appeared:
![image](https://user-images.githubusercontent.com/130743913/236838465-a474cb7e-d35a-4bfd-b9a7-ec04cf8d8f32.png)

Do you know what that means and how I can solve it?

Thanks in advance!

**Comment by BjornNyberg** [comment]
Hi @fristena 
Are you on a windows machine? If so, did you use the configure tool as described in the installation [guide](https://github.com/BjornNyberg/NetworkGT/wiki/Installation)? 

If your on macOSX or linux, you need to identify which python version is connected to QGIS and install the packages there.

**Comment by fristena** [comment]
Hi Bjorn

Yes, I'm on a windows machine and I did not use the configure tool. Now it worked. Thank you very much!

Cheers, 
Arabella
