### ISSUE TITLE
rose digram

### ISSUE THREAD

**Issue by Ay0a** [BjornNyberg/NetworkGT#34]
Hi
I can't solve this problem 
<img width="960" alt="2023-05-09 (1)" src="https://user-images.githubusercontent.com/132994042/237042967-10fd6d0b-6053-4517-aaf0-d08d5424479b.png">

**Comment by BjornNyberg** [comment]
Hi @Ay0a 

Is this the same problem that is reported [here](https://github.com/BjornNyberg/NetworkGT/issues/33) possibly?

**Comment by Ay0a** [comment]
Dear Bjorn Nyberg,

Thank you for your reply, yes its tha same i did the configure tool and it
work. Thank you

Best regards,
Aya
