### ISSUE TITLE
Grid E-Nodes

### ISSUE THREAD

**Issue by xxostars** [BjornNyberg/NetworkGT#35]
hi
why there is a huge amount of Grid E-nodes within the interpretation boundary when we want to create the topology parameters? what is the importance of it for the topology?
<img width="604" alt="Screenshot 2023-05-26 113347" src="https://github.com/BjornNyberg/NetworkGT/assets/127874728/63bd0c4b-aa67-45cf-9aae-d902f78b0e80">

**Comment by xxostars** [comment]
also why is the number of grid node being more than the normal nodes? what is the purpose of this?

**Comment by BjornNyberg** [comment]
Hi @xxostars 

This is not a bug but a design feature. Edge nodes describe the edge of the sampling area. It is primarily used to calculate the number of blocks. Please read the paper available [here](https://pubs.geoscienceworld.org/geosphere/article-pdf/14/4/1618/4265316/1618.pdf) for more information.
