### ISSUE TITLE
Error Block Analysis

### ISSUE THREAD

**Issue by fristena** [BjornNyberg/NetworkGT#36]
Hi Bjorn

I'm trying to use the "identify blocks" tool, however following error occurs: 

![image](https://github.com/BjornNyberg/NetworkGT/assets/130743913/5a24ac72-83b3-4a25-94dd-fd81e3b6ba79)

Do you have an idea why that could be? 

Thanks in advance
Arabella

**Comment by BjornNyberg** [comment]
Hi @fristena 

No i havent encountered this error before. Can you perhaps send a copy so that I may replicate the issue?

Cheers,
Björn

**Comment by fristena** [comment]
Hi Bjorn, 

Thank you for your quick reply. 

I tested it again and by creating a temporaty layer of the identified blocks it worked somehow. 

Sorry for the inconvenience!

Cheers, 
Arabella
