### ISSUE TITLE
Digitise Fracture network GrassGIS error

### ISSUE THREAD

**Issue by okaragoz** [BjornNyberg/NetworkGT#37]
Hi,
When I run Digitise Fracture network, I get the following error: 'grass7r:vec. not found' even though I have GrassGIS installed.
<img width="1828" alt="image" src="https://github.com/BjornNyberg/NetworkGT/assets/10538116/335a3c02-b3e2-40b9-acab-077f4888723c">

**Comment by BjornNyberg** [comment]
@okaragoz 

If you have a newer version of QGIS, you may have to activate GRASS in the processing toolbox. Have a look [here](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/FAQ) for more info. Does that resolve your problem?

**Comment by okaragoz** [comment]
Hi @BjornNyberg, thanks for a quick reply.
When I check the processing settings to activate GRASS, I could not see any kind of activate button. When I checked the rendering settings to activate GRASS, I didn't see any activation button. I read a few comments that it should come activated in Windows, but I can't run any package of GRASS in the toolbox. I guess I need to solve this problem first. Anyway, thanks for your help.  

<img width="1856" alt="image" src="https://github.com/BjornNyberg/NetworkGT/assets/10538116/109757e8-323b-4367-8831-57b86173e89a">

**Comment by BjornNyberg** [comment]
Hi @okaragoz 

Yes you are indeed correct that it should be automatically activated (once you install it through the plugin manager - make sure that both the plugin and GRASS 8 are installed). Can you check if any of your GRASS tools work? I notice that the current version is shipped with GRASS v8 whereas the digitize tool uses GRASS v7 - this means that perhaps the tool needs to be updated from my end.
