### ISSUE TITLE
ERROR 000732: Input Excel File: Dataset temp_table.xls does not exist or is not supported

### ISSUE THREAD

**Issue by SeyedTohid** [BjornNyberg/NetworkGT#38]
Dear Dr. Nyberg

Hello. I hope you are doing well.

Recently I'm working on topology of fracture and fault networks and using NetworkGT GIS-based toolbar (version 0.99) for that. However, I have a problem with this toolbar, so that I did all the steps according to the toolbar guide and it categorizes the fractures into nodes and branches types (I, Y, X) (attached files) (i.e. subsection 3.3.1. Branches and Nodes in user guide), but when I want to show the final step as a color distribution of fracture connectivity, node distribution etc. and also plots on the fracture topology triangle diagrams, it gives an error, as the following (especially on the Excel file that I don't know what is that file and where is that file?!). Hence, your help and guidance are needed to solve this problem.

I extracted the fractures in the graphics software from a field photograph and used them in the format .svg in Arc GIS sotfware in order to topology analysis. I'm also using Arc GIS 10.8. Do you recommend using the QGIS software instead of Arc GIS?

Thank you
Best regards,
Tohid

![44329eb6-a91f-4739-86dd-aaf8d257c0b7](https://github.com/BjornNyberg/NetworkGT/assets/141872967/4db5cae5-910a-4c35-96b9-6ac89cd9ea65)
![67022759-aa17-4f3e-b976-6c6d723588e2](https://github.com/BjornNyberg/NetworkGT/assets/141872967/704e557c-3f4e-4ae7-bfc1-60c0f42b22fc)
![f32181d8-7712-4729-b501-9c0aeff30da0](https://github.com/BjornNyberg/NetworkGT/assets/141872967/88f13177-dc59-4f15-85d9-3bd05c580da9)
![fca635c2-3b33-4bcc-b50b-1bce14a25ba1](https://github.com/BjornNyberg/NetworkGT/assets/141872967/a6f14ec4-d524-4432-a725-e8f57f8df832)

**Comment by BjornNyberg** [comment]
Hi @SeyedTohid

Im not sure of the exact cause of this issue but the ArcGIS toolbox is currently not supported anymore. Part of the reason is to only maintain one system that is open-access but also the original code was written in python 2.x which is now depreciated. I would recommend using the QGIS version which you can get more help [here](https://github.com/BjornNyberg/NetworkGT/wiki).

**Comment by SeyedTohid** [comment]
> Hi @SeyedTohid
> 
> Im not sure of the exact cause of this issue but the ArcGIS toolbox is currently not supported anymore. Part of the reason is to only maintain one system that is open-access but also the original code was written in python 2.x which is now depreciated. I would recommend using the QGIS version which you can get more help [here](https://github.com/BjornNyberg/NetworkGT/wiki).

Thank you so much for your clear answer and guidance.
Best regards,
