### ISSUE TITLE
No module named skimage

### ISSUE THREAD

**Issue by lucasprosa** [BjornNyberg/NetworkGT#40]
loading module error What would be the procedure?
![Captura de tela 2024-04-23 233223](https://github.com/BjornNyberg/NetworkGT/assets/167945898/d798792d-d423-440e-88a7-d8dd92cfbc43)

**Comment by BjornNyberg** [comment]
@lucasprosa Did you follow the installation guideline? https://github.com/BjornNyberg/NetworkGT/wiki/Installation

**Comment by BjornNyberg** [comment]
@lucasprosa im closing this issue for now but feel free to reopen if the issue continues
