### ISSUE TITLE
Repair Network -tool issues

### ISSUE THREAD

**Issue by nialov** [BjornNyberg/NetworkGT#7]
The repair network tool is faulty in my QGIS version 3.12.0.

### Two issues:

- In Repair.py: Looking up the field index of 'Fault No' will fail due to QGIS using underscore (_) as a replacement for space. Changing 'Fault No' to 'Fault_No' will fix this issue. However, I do not quite understand why editing the original layer by adding this 'Fault No' index is required?

- The repair tool creates artifacts at X-intersections. See image. I can supply my datasets if required. **Update: Having some trouble repeating the artifacts, might've been some faulty inputs.**

![x_node_artifacts](https://user-images.githubusercontent.com/47318483/78469827-266af980-772d-11ea-84ad-5b24eb690f30.JPG)

**Comment by BjornNyberg** [comment]
The issues appear related to the fact that QGIS is not fully topologically accurate. Try increasing the Precision parameter in the repair.py script. The Fault No is indeed not required and was part of an earlier version. An updated version of the toolbox will hopefully resolve this issue and the fault no but I will keep this issue open until the new version is released.

**Comment by nialov** [comment]
I got great results by fixing the topology with a (built-in) GRASS plugin:
https://grass.osgeo.org/grass78/manuals/v.clean.html
