### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by saulogmenezes** [BjornNyberg/NetworkGT#9]
When I run the "Topology Parameter" option I get such error:

Reading Data
1 Grid Samples
277 Nodes
277 Branches
Traceback (most recent call last):

File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

It seems that the problem is the version of Pandas but I do not know... Could you help me?

**Comment by BjornNyberg** [comment]
@saulogmenezes ix has been removed in later version of pandas and this needs to be updated. Please install pandas==0.25.1 to fix.

**Comment by saulogmenezes** [comment]
Thank you Bjorn! It worked fine! Congratulations on the plugin.
